// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/daftar": {
            "post": {
                "description": "Create For Account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "API Create Account",
                "parameters": [
                    {
                        "description": "Request Parameters",
                        "name": "CreateAccountRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accountModel.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/accountModel.CreateAccountResponse"
                        }
                    }
                }
            }
        },
        "/inquiry": {
            "get": {
                "description": "Inquiry For Account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "API Inquiry Account",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Basic NjI4MjE2NzU1MzYzNDQwMDAxOjEyMzQ1Ng==",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/accountModel.Account"
                        }
                    }
                }
            }
        },
        "/tabung": {
            "post": {
                "description": "Saving For Account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "API Saving Account",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Basic NjI4MjE2NzU1MzYzNDQwMDAxOjEyMzQ1Ng==",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request Parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transactionModel.SavingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/transactionModel.TransactionResponse"
                        }
                    }
                }
            }
        },
        "/tarik": {
            "post": {
                "description": "CashWithdrawl For Account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "API CashWithdrawl Account",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Basic NjI4MjE2NzU1MzYzNDQwMDAxOjEyMzQ1Ng==",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request Parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transactionModel.CashWithdrawlRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response Success",
                        "schema": {
                            "$ref": "#/definitions/transactionModel.TransactionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "accountModel.Account": {
            "type": "object",
            "properties": {
                "account_no": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                }
            }
        },
        "accountModel.CreateAccountRequest": {
            "type": "object",
            "required": [
                "name",
                "phone_number",
                "pin"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "pin": {
                    "type": "string"
                }
            }
        },
        "accountModel.CreateAccountResponse": {
            "type": "object",
            "required": [
                "account_no",
                "balance"
            ],
            "properties": {
                "account_no": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                }
            }
        },
        "transactionModel.CashWithdrawlRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "minimum": 1
                }
            }
        },
        "transactionModel.SavingRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "minimum": 1
                }
            }
        },
        "transactionModel.TransactionResponse": {
            "type": "object",
            "required": [
                "account_no",
                "balance"
            ],
            "properties": {
                "account_no": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Account Swagger API Documentation",
	Description:      "This is API Documentation for Account Swagger Services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
